[project]
name = "multimodal-data-analysis-using-openai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.5",
    "openai>=2.18.0",
    "pandas>=3.0.0",
]
